import React from "react";

export default {
  name: 'Sobhan Sharafi',
  login: 'LOGIN',
  signin: 'NEW USER',
  welcome: 'Welcome',
  googleSignIn: 'Sign in with Google',
  or: 'or',
  emailAddress: 'Email Address',
  password: 'Password',
  forgetPassword: 'ForgetPassword',
  copyRight: 'All rights belong to Sobhan Sharafi.',
  createYourAccout: 'Create your account',
  fullName: 'Full Name',
  createAccount: 'Create your account',
  lastReports: 'LASTEST REPORTS',
  dashboard: 'HOME',
  visitsToday: 'Visits Today',
  registrations: 'Registrations',
  signOut: 'Sign Out',
  rate: 'Rate',
  edit: 'Edit',
  copy: 'Copy',
  delete: 'Delete',
  print: 'Print',
  appPerformance: 'App Performance',
  integration: 'Integration',
  serverOverview: 'Server Overview',
  revenueBreakdown: 'Revenue Breakdown\n',
  group: 'Group ',
  first: 'A',
  second: 'B',
  third: 'C',
  forth: 'D',
  dailyLineChart: 'Daily Line Chart',
  tablet: 'Tablet',
  mobile: 'Mobile',
  desktop: 'Desktop',
  daily: 'Daily',
  monthly: 'Monthly',
  weekly: 'Weekly',
  product1: 'Light Blue',
  product2: 'Sing App',
  product3: 'RNS',
  bounceRate: 'Bounce Rate',
  visit: 'Views',
  supportRequests: 'Support Requests',
  NAME: 'NAME',
  EMAIL: 'EMAIL',
  PRODUCT: 'PRODUCT',
  PRICE: 'PRICE',
  DATE: 'DATE',
  CITY: 'CITY',
  STATUS: 'STATUS',
  SENT: 'Sent',
  PENDING: 'Pending',
  DECLINED: 'Declined',
  aboutUs: 'About us',
  typography: 'Typography',
  tables: 'Tables',
  notifications: 'Notifications',
  UIElements: 'UI Elements',
  icons: 'Icons',
  charts: 'Charts',
  maps: 'Maps',
  help: 'Help',
  library: 'Library',
  support: 'Support',
  faq: 'FAQ',
  projects: 'Projects',
  headings: 'Headings',
  typographyColors: 'Typography Colors',
  basicTextSettings: 'Basic Text Settings',
  textSize: 'Text Size',
  basicText: 'Basic text',
  basicLightText: 'Basic light text',
  basicMediumText: 'Basic medium text',
  basicBoldText: 'Basic bold text',
  basicUpperCaseText: 'BASIC UPPERCASE TEXT',
  basicLowercaseText: 'basic lowercase text',
  basicCapitalizedText: 'Basic Capitalized Text',
  basicCursiveText: 'Basic Cursive Text',
  headingTypographyFontSize: 'Heading Typography ',
  state: 'State',
  company: 'Company',
  employeeList: 'Employee List',
  nextPage: 'Next Page',
  previousPage: 'Previous Page',
  rowsPerPage: 'Rows per page:',
  displayRows: 'of',
  search: 'Search',
  downloadCsv: 'Download CSV',
  Print: 'Print',
  viewColumns: 'View Columns',
  filterTable: 'Filter Table',
  reset: 'Reset',
  filterTitle: 'FILTERS',
  deleteText: ' row(s) selected',
  deleteButtonText: 'Delete',
  layoutOptions: 'Layout Options',
  layoutOptionsText: 'There are few position options available for notifications. You can click any of them to change notifications position:',
  clickAnyPosition: 'Click any position',
  notificationsTypes: 'Notifications Types',
  notificationsTypesText: 'Different types of notifications for lost of use cases. Custom classes are also supported.',
  infoMessage: 'Info Message',
  ErrorRetryMessage: 'Error + Retry Message',
  successMessage: 'Success Message',
  usage: 'Usage',
  usageText: 'Notifications are created with the help of  ',
  usageText2: 'For more API information refer to the library documentation',
  create: '',
  notificationTypesExamples: 'Notification Types Examples',
  thanksForCheckingOutMessenger: 'Thanks for Checking out Messenger',
  newUserFeedbackReceived: 'New user feedback received',
  newCustomerIsRegistered: 'New customer is registered',
  theOrderWasShipped: 'The order was shipped',
  theOrderWasDelivered: 'The order was delivered',
  defenceAlerts: '5 Defence alerts',
  newReportHasBeenReceived: 'New report has been received',
  newMessageText: 'The new message from user Sobhan Sharafi ',
  youFileIsReadyToUpload: 'Your file is ready to upload',
  theDiscIsFull: 'دThe disc is full',
  messageWasNotSent: 'Message was not sent!',
  resend: 'Resend',
  chartsPageTitle: 'Charts Page - Data Display',
  latestReports: 'LASTEST REPORTS',
  apexLineChart: 'Apex Line Chart',
  apexHeatmap: 'Apex Heatmap',
  simpleLineChart: 'Simple Line Chart',
  pieChartWithTooltips: 'Pie Chart with Tooltips',
  actions: 'ACTIONS',
  sendNewMessage: 'Send New Message',
  newMessages: 'New Messages',
  profile: 'Profile',
  tasks: 'Tasks',
  messages: 'Messages',
  SignOut: 'Sign Out',
  emailErrorText: 'The entered email is not valid',
  passwordErrorText: 'Password must contain at least 6 characters.',
  fullNameErrorText: 'The full name cannot contain the characters $ -% - # - @ -! - * - and ...',
  settings: 'Settings'
};