import React from "react";

export default {
    name: 'سبحان شرفی',
    login: 'ورود',
    signin: 'ثبت نام',
    welcome: 'خوش امدید',
    googleSignIn: 'ورود با گوگل',
    or: 'یا',
    emailAddress: 'ادرس ایمیل',
    password: 'رمز عبور',
    forgetPassword: 'فراموشی رمز عبور',
    copyRight: 'کلیه حقوق متعلق به سبحان شرفی میباشد.',
    createYourAccout: 'حساب کاربری خود را بسازید.',
    fullName: 'نام کامل',
    createAccount: 'ساخت حساب',
    lastReports: 'اخرین گزارشات',
    dashboard: 'خانه',
    visitsToday: 'بازدید امروز',
    registrations: 'ثبت نام ها',
    signOut: 'خروج از سیستم',
    rate: 'نرخ',
    edit: 'ویرایش',
    copy: 'کپی',
    delete: 'حذف',
    print: 'چاپ',
    appPerformance: 'عملکرد برنامه',
    integration: 'اختلاط',
    serverOverview: 'بررسی اجمالی سرور',
    revenueBreakdown: 'تجزیه درآمد',
    group: 'گروه ',
    first: 'اول',
    second: 'دوم',
    third: 'سوم',
    forth: 'چهارم',
    dailyLineChart: 'نمودار خطی روزانه',
    tablet: 'تبلت',
    mobile: 'موبایل',
    desktop: 'دسکتاپ',
    daily: 'روزانه',
    monthly: 'ماهانه',
    weekly: 'هفتگی',
    product1: 'محصول اول',
    product2: 'محصول دوم',
    product3: 'محصول سوم',
    bounceRate: 'نرخ گزاف گویی',
    visit: 'بازدید',
    supportRequests: 'درخواست های پشتیبانی',
    NAME: 'نام',
    EMAIL: 'ایمیل',
    PRODUCT: 'محصول',
    PRICE: 'قیمت',
    DATE: 'تاریخ',
    CITY: 'شهر',
    STATUS: 'وضعیت',
    SENT: 'ارسال شد',
    PENDING: 'در صف ارسال',
    DECLINED: 'تایید نشده',
    aboutUs: 'درباره ما',
    typography: 'تایپوگرافی',
    tables: 'جدول ها',
    notifications: 'اعلان ها',
    UIElements: 'عناصر رابط کابری',
    icons: 'ایکون ها',
    charts: 'نمودار ها',
    maps: 'نقشه ها',
    help: 'راهنمایی',
    library: 'کتاب خانه ها',
    support: 'پشتیبانی',
    faq: 'سوالات متداول',
    projects: 'پروژه ها',
    headings: 'عناوین',
    typographyColors: 'رنگ های تایپوگرافی',
    basicTextSettings: 'تنظیمات اساسی متن',
    textSize: 'اندازه متن',
    basicText: 'متن ساده',
    basicLightText: 'متن روشن ساده',
    basicMediumText: 'متن متوسط ساده',
    basicBoldText: 'متن پررنگ ساده',
    basicUpperCaseText: 'متن حروف بزرگ',
    basicLowercaseText: 'متن حرف کوچیک',
    basicCapitalizedText: 'متن بزرگ شده',
    basicCursiveText: 'متن شکسته',
    headingTypographyFontSize: 'عنوان تایپو گرافی',
    state: 'ایالت',
    company: 'شرکت',
    employeeList: 'لیست کارمندها',
    nextPage: 'صفحه بعد',
    previousPage: 'صفحه قبل',
    rowsPerPage: 'تعداد ردیف های هر صفحه:',
    displayRows: 'از',
    search: 'جستجو',
    downloadCsv: 'دانلود Csv',
    Print: 'چاپ',
    viewColumns: 'نشان دادن ردیف ها',
    filterTable: 'فیلتر',
    reset: 'پاک کردن',
    filterTitle: 'فیلتر',
    deleteText: 'حذف ردیف(ها)',
    deleteButtonText: 'حذف',
    layoutOptions: 'گزینه های طرح بندی',
    layoutOptionsText: 'گزینه های موقعیت کمی برای اعلان ها موجود است. برای تغییر موقعیت اعلان ها می توانید روی هر یک از آنها کلیک کنید:',
    clickAnyPosition: 'روی هر موقعیتی کلیک کنید',
    notificationsTypes: 'انواع اعلان ها',
    notificationsTypesText: 'انواع مختلف اعلان ها برای بیشتر موارد. همچنین شما میتونید انها را شخصی سازی کنید.',
    infoMessage: 'پیام اطلاعاتی',
    ErrorRetryMessage: 'خطا + پیام تلاش دوباره',
    successMessage: 'پیام موفقیت امیز',
    usage: 'نحوه استفاده',
    usageText: 'اعلان ها با کمک ',
    usageText2: 'برای اطلاعات بیشتر به اسناد کتابخانه مراجعه کنید',
    create: ' ایجاد می شوند ',
    notificationTypesExamples: 'نمونه انواع اعلان ها',
    thanksForCheckingOutMessenger: 'بابت بررسی پیام ها از شما متشکریم',
    newUserFeedbackReceived: 'بازخورد کاربر جدید دریافت شد',
    newCustomerIsRegistered: 'کاربر جدید ثبت نام کرد',
    theOrderWasShipped: 'سفارش حمل شد',
    theOrderWasDelivered: 'سفارش تحویل داده شد',
    defenceAlerts: '5 هشدار دفاع',
    newReportHasBeenReceived: 'گزارش جدید دریافت شد',
    newMessageText: 'پیام جدید از کاربر sobhan-sharafi ',
    youFileIsReadyToUpload: 'فایل شما آماده بارگذاری است',
    theDiscIsFull: 'دیسک پر است',
    messageWasNotSent: 'پیام ارسال نشد!',
    resend: 'ارسال مجدد',
    chartsPageTitle: 'صفحه نمودار ها - نمایش دادن داده ها',
    latestReports: 'اخرین گزارشات',
    apexLineChart: 'نمودار خط اوج',
    apexHeatmap: 'نمودار حرارت',
    simpleLineChart: 'نمودار خطی ساده',
    pieChartWithTooltips: 'نمودار دایره ای با راهنما',
    actions: 'عملیات',
    sendNewMessage: 'ارسال پیام جدید',
    newMessages: 'پیام جدید',
    profile: 'مشخصات',
    tasks: 'وظایف',
    messages: 'پبام ها',
    SignOut: 'خروج',
    emailErrorText: 'فرمت ایمیل وارد شده صحیح نمی باشد.',
    passwordErrorText: 'پسورد باید حداقل شامل 6 کاراکتر باشد.',
    fullNameErrorText: 'نام نمیتواند شامل کاراکتر های $-%-#-@-!-*- و ... باشد.',
    settings: 'تنظیمات'
};